# Distinct Powers - https://projecteuler.net/problem=29

def distinct_powers(min_base, max_base, min_exp, max_exp):
    distinct_terms = set()
    
    for base in range(min_base, max_base + 1):
        for exp in range(min_exp, max_exp + 1):
            distinct_terms.add(base ** exp)
    
    return len(distinct_terms)


if __name__ == "__main__":
    result = distinct_powers(2, 100, 2, 100)
    print(f"The number of distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100 is: {result}")